server:
  port: 80

  #Eureka配置
eureka:
  client:
   # register-with-eureka: false #不向Eureka中注册自己
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka

ribbon: #就是配置了一下这里，还有就是要先启动提供方。好了 谢谢
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间


springcloud-provider-dept: #两个地方，一个是eureka的地址错了，一个是这里需要配置   好了。感谢 支付宝发我下
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  #或启动类上@RibbonClient(naem="user-service",configuration="MyRule.class");//配置类对象MyRule.class中注册bean  new **Rule();        MyRule.class最好不在启动类中，并且加上configuration