server:
  port: 7001
#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己

    fetch-registry: false #如果为false，则表示自己为注册中心
    service-url:  #监控页面
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群（关联）：
      defaultZone: http://127.0.0.1:7003/eureka,http://127.0.0.1:7002/eureka
  #register-with-eureka: false 这句作用就是不注册自己到注册中心，这样就实现了既不报错也不注册自己

