server:
  port: 8001

mybatis:
  type-aliases-package: com.hui.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:  #你的错误有点多啊。，，做映射了 这些不都一样么 映射到了127哦，端口不是80做映射是不是不可以，我也不知道，，。。。
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka上的默认信息


#info配置
info:
  app.name: hui-springcloud
  company.name: blog.hui.com